server:
  port: ${API_PORT_DEFAULT:8092}
  servlet.context-path: /notificar-usuarios

spring:
  application:
    name: ${API_NAME_DEFAULT:notificar-usuarios}

  messages:
    basename: messages
    encoding: UTF-8

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

app:
  kafka:
    consumers:

      usuario:
        group-id: usuario-consumer
        criado.topic: usuario-criado
        atualizado.topic: usuario-atualizado

      agendamento:
        group-id: agendamento-consumer
        criado.topic: agendamento-criado
        atualizado.topic: agendamento-atualizado